In [1]:
import pandas as pd

In [2]:
users = pd.read_csv(
    "users.dat",
    sep="::",
    engine="python",
    names=["UserID","Gender","Age","Occupation","ZipCode"]
)

users.head()

   UserID Gender  Age  Occupation ZipCode
0       1      F    1          10   48067
1       2      M   56          16   70072
2       3      M   25          15   55117
3       4      M   45           7   02460
4       5      M   25          20   55455

In [5]:
# Load the Movies dataset
# The encoding is set to 'latin-1' to correctly read special characters in movie titles.

movies = pd.read_csv(
    "movies.dat",
    sep="::",
    engine="python",
    encoding="latin-1",
    names=["MovieID","Title","Genres"]
)

movies.head()

   MovieID                               Title                        Genres
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy

In [6]:
ratings = pd.read_csv(
    "ratings.dat",
    sep="::",
    engine="python",
    names=["UserID","MovieID","Rating","Timestamp"]
)

ratings.head()

   UserID  MovieID  Rating  Timestamp
0       1     1193       5  978300760
1       1      661       3  978302109
2       1      914       3  978301968
3       1     3408       4  978300275
4       1     2355       5  978824291

In [8]:
ratings["Timestamp"] = pd.to_datetime(ratings["Timestamp"], unit="s")

ratings.head()

   UserID  MovieID  Rating           Timestamp
0       1     1193       5 2000-12-31 22:12:40
1       1      661       3 2000-12-31 22:35:09
2       1      914       3 2000-12-31 22:32:48
3       1     3408       4 2000-12-31 22:04:35
4       1     2355       5 2001-01-06 23:38:11

In [9]:
users["Gender"] = users["Gender"].map({
    "F":0,
    "M":1
})

users.head()

   UserID  Gender  Age  Occupation ZipCode
0       1       0    1          10   48067
1       2       1   56          16   70072
2       3       1   25          15   55117
3       4       1   45           7   02460
4       5       1   25          20   55455

In [10]:
movies["Genres"] = movies["Genres"].str.split("|")

movies.head()

,MovieID,Title,Genres
0,1,Toy Story (1995),"[Animation, Children's, Comedy]"
1,2,Jumanji (1995),"[Adventure, Children's, Fantasy]"
2,3,Grumpier Old Men (1995),"[Comedy, Romance]"
3,4,Waiting to Exhale (1995),"[Comedy, Drama]"
4,5,Father of the Bride Part II (1995),[Comedy]

In [11]:
users.to_parquet("users.parquet", index=False)
movies.to_parquet("movies.parquet", index=False)
ratings.to_parquet("ratings.parquet", index=False)

In [12]:
users_parquet = pd.read_parquet("users.parquet")
movies_parquet = pd.read_parquet("movies.parquet")
ratings_parquet = pd.read_parquet("ratings.parquet")

users_parquet.head()

   UserID  Gender  Age  Occupation ZipCode
0       1       0    1          10   48067
1       2       1   56          16   70072
2       3       1   25          15   55117
3       4       1   45           7   02460
4       5       1   25          20   55455